const projects = [
  {
    id: 5,
    title: 'Discord TanukiBot',
    desc: 'My personalize Discord Bot coded in NodeJS using the WOKCommands library.',
    imgSrc: '/assets/Discordbot.webp',
    designer: 'Pom Poko',
    coder: 'Pom Poko',
    techs: ['TS', 'NodeJS', 'MongoDB'],
    src: 'https://github.com/PomPoko-lab/TanukiBot-Node',
    demo: 'https://github.com/PomPoko-lab/TanukiBot-Node',
  },
  {
    id: 4,
    title: 'Bite Diary',
    desc: 'A recipe diary designed to record family and friend recipes, mostly family delicacies. Recipes may be created, updated, and deleted from the app.',
    imgSrc: '/assets/bite-diary-homepage.webp',
    designer: 'Pom Poko',
    coder: 'Pom Poko',
    techs: ['HTML', 'CSS', 'JS', 'ReactJS', 'Firebase'],
    src: 'https://github.com/PomPoko-lab/bite-diary',
    demo: 'https://recipes.pompoko.io/',
  },
  {
    id: 1,
    title: 'FFXIV Restaurant Page',
    desc: "An intro to React project made for my guild on Final Fantasy XIV. The project features a restaurant web page playing off of the guild's theme.",
    imgSrc: '/assets/restaurant-page.jpg',
    designer: 'Pom Poko',
    coder: 'Pom Poko',
    techs: ['HTML', 'CSS', 'JS', 'React'],
    src: 'https://github.com/PomPoko-lab/restaurant-page',
    demo: 'https://pompoko.io/restaurant-page/',
  },
  {
    id: 2,
    title: 'Portfolio',
    desc: "Source of the page you're currently viewing.",
    imgSrc: '/assets/portfolio-page.jpg',
    designer: 'Pom Poko',
    coder: 'Pom Poko',
    techs: ['HTML', 'CSS', 'JS', 'ReactJS'],
    src: 'https://github.com/PomPoko-lab/pompoko-lab.github.io',
    demo: 'https://pompoko.io/',
  },
  {
    id: 3,
    title: 'Lost Ark Tools',
    desc: "My intro to JS personal project. After Lost Ark NA's (PC Game) initial launch, these tools were created to assist me in daily gaming chores. Features a daily tracker and in-game currency shop calculator.",
    imgSrc: '/assets/lostarktools.webp',
    designer: 'Pom Poko',
    coder: 'Pom Poko',
    techs: ['HTML', 'CSS', 'JS'],
    src: 'https://github.com/PomPoko-lab/lost-ark-tools',
    demo: 'https://pompoko.io/lost-ark-tools/',
  },
];

export default projects;
