const projects = [
  {
    id: 1,
    title: 'FFXIV Restaurant Page',
    desc: "An intro to React project made for my guild on Final Fantasy XIV. The project features a restaurant web page playing off of the guild's theme.",
    imgSrc: '/assets/restaurant-page.jpg',
    designer: 'Pom Poko',
    coder: 'Pom Poko',
    techs: ['HTML', 'CSS', 'JS', 'React', 'ChakraUI', 'ChocUI'],
    src: 'https://github.com/PomPoko-lab/restaurant-page',
    demo: 'https://pompoko.io/restaurant-page/',
  },
  {
    id: 2,
    title: 'Portfolio',
    desc: "Source of the page you're currently viewing.",
    imgSrc: '/assets/portfolio-page.jpg',
    designer: 'Pom Poko',
    coder: 'Pom Poko',
    techs: ['HTML', 'CSS', 'JS', 'React', 'React Router', 'ChakraUI'],
    src: 'https://github.com/PomPoko-lab/pompoko-lab.github.io',
    demo: 'https://pompoko.io/',
  },
  {
    id: 3,
    title: 'Lost Ark Tools',
    desc: "My intro to JS personal project. After Lost Ark NA's (PC Game) initial launch, these tools were created to assist me in daily gaming chores. Features a daily tracker and in-game currency shop calculator.",
    imgSrc: '/assets/lostarktools.webp',
    designer: 'Pom Poko',
    coder: 'Pom Poko',
    techs: ['HTML', 'CSS', 'JS'],
    src: 'https://github.com/PomPoko-lab/lost-ark-tools',
    demo: 'https://pompoko.io/lost-ark-tools/',
  },
  {
    id: 4,
    title: 'Recipe Journal App UPCOMING',
    desc: 'An app written to track recipes from family and friends. The app will feature adding new recipes and fetching recipes from APIs.',
    imgSrc: '/assets/projectUpcoming.jpg',
    designer: 'Pom Poko',
    coder: 'Pom Poko',
    techs: ['HTML', 'CSS', 'JS', 'React', 'ChakraUI', 'ChocUI', 'Firebase'],
    src: '#',
    demo: '#',
  },
];

export default projects;
